/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Z8YKkJHS3GS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Button } from "@/components/ui/button"

export function Main() {
  return (
    <div className="w-full">
      <div className="relative overflow-hidden">
        <Carousel className="w-full max-w-6xl mx-auto" opts={{ loop: true, autoplay: true, autoplaySpeed: 3000 }}>
          <CarouselContent>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={500}
                className="object-cover w-full h-[500px]"
                style={{ aspectRatio: "1200/500", objectFit: "cover" }}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={500}
                className="object-cover w-full h-[500px]"
                style={{ aspectRatio: "1200/500", objectFit: "cover" }}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={500}
                className="object-cover w-full h-[500px]"
                style={{ aspectRatio: "1200/500", objectFit: "cover" }}
              />
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </div>
      <section className="py-12 md:py-16 lg:py-20">
        <div className="container px-4 md:px-6">
          <h2 className="text-2xl font-bold mb-8 md:text-3xl">Papelería</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <div className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt="Product"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium mb-2">Cuaderno de Notas</h3>
                <p className="text-muted-foreground mb-4">Cuaderno de notas con portada de diseño panamericano.</p>
                <div className="flex items-center justify-between">
                  <span className="text-primary font-medium">$9.99</span>
                  <Button size="sm">Agregar al carrito</Button>
                </div>
              </div>
            </div>
            <div className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt="Product"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium mb-2">Bolígrafo de Madera</h3>
                <p className="text-muted-foreground mb-4">
                  Bolígrafo de madera con diseño inspirado en la cultura panamericana.
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-primary font-medium">$4.99</span>
                  <Button size="sm">Agregar al carrito</Button>
                </div>
              </div>
            </div>
            <div className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt="Product"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium mb-2">Lápices de Colores</h3>
                <p className="text-muted-foreground mb-4">
                  Set de lápices de colores con diseños inspirados en la cultura panamericana.
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-primary font-medium">$12.99</span>
                  <Button size="sm">Agregar al carrito</Button>
                </div>
              </div>
            </div>
            <div className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt="Product"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium mb-2">Agenda de Escritorio</h3>
                <p className="text-muted-foreground mb-4">
                  Agenda de escritorio con diseño inspirado en la cultura panamericana.
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-primary font-medium">$14.99</span>
                  <Button size="sm">Agregar al carrito</Button>
                </div>
              </div>
            </div>
          </div>
          <div className="flex justify-center mt-8">
            <Button variant="outline">Ver más</Button>
          </div>
        </div>
      </section>
      <div className="relative overflow-hidden">
        <Carousel className="w-full max-w-6xl mx-auto" opts={{ loop: true, autoplay: true, autoplaySpeed: 3000 }}>
          <CarouselContent>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={300}
                className="object-cover w-full h-[300px]"
                style={{ aspectRatio: "1200/300", objectFit: "cover" }}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={300}
                className="object-cover w-full h-[300px]"
                style={{ aspectRatio: "1200/300", objectFit: "cover" }}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={300}
                className="object-cover w-full h-[300px]"
                style={{ aspectRatio: "1200/300", objectFit: "cover" }}
              />
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </div>
      <section className="py-12 md:py-16 lg:py-20 bg-muted">
        <div className="container px-4 md:px-6">
          <h2 className="text-2xl font-bold mb-8 md:text-3xl">Regalos</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            <div className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt="Product"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium mb-2">Taza de Cerámica</h3>
                <p className="text-muted-foreground mb-4">
                  Taza de cerámica con diseño inspirado en la cultura panamericana.
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-primary font-medium">$14.99</span>
                  <Button size="sm">Agregar al carrito</Button>
                </div>
              </div>
            </div>
            <div className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt="Product"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium mb-2">Bolsa de Tela</h3>
                <p className="text-muted-foreground mb-4">
                  Bolsa de tela con diseño inspirado en la cultura panamericana.
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-primary font-medium">$9.99</span>
                  <Button size="sm">Agregar al carrito</Button>
                </div>
              </div>
            </div>
            <div className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt="Product"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium mb-2">Portarretratos</h3>
                <p className="text-muted-foreground mb-4">
                  Portarretratos de madera con diseño inspirado en la cultura panamericana.
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-primary font-medium">$19.99</span>
                  <Button size="sm">Agregar al carrito</Button>
                </div>
              </div>
            </div>
            <div className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt="Product"
                width={400}
                height={300}
                className="w-full h-48 object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="p-4">
                <h3 className="text-lg font-medium mb-2">Caja de Madera</h3>
                <p className="text-muted-foreground mb-4">
                  Caja de madera con diseño inspirado en la cultura panamericana.
                </p>
                <div className="flex items-center justify-between">
                  <span className="text-primary font-medium">$24.99</span>
                  <Button size="sm">Agregar al carrito</Button>
                </div>
              </div>
            </div>
          </div>
          <div className="flex justify-center mt-8">
            <Button variant="outline">Ver más</Button>
          </div>
        </div>
      </section>
      <div className="relative overflow-hidden">
        <Carousel className="w-full max-w-6xl mx-auto" opts={{ loop: true, autoplay: true, autoplaySpeed: 3000 }}>
          <CarouselContent>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={300}
                className="object-cover w-full h-[300px]"
                style={{ aspectRatio: "1200/300", objectFit: "cover" }}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={300}
                className="object-cover w-full h-[300px]"
                style={{ aspectRatio: "1200/300", objectFit: "cover" }}
              />
            </CarouselItem>
            <CarouselItem>
              <img
                src="/placeholder.svg"
                alt="Featured Product"
                width={1200}
                height={300}
                className="object-cover w-full h-[300px]"
                style={{ aspectRatio: "1200/300", objectFit: "cover" }}
              />
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </div>
    </div>
  )
}
