/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/RxuOb7na6M4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink } from "@/components/ui/navigation-menu"
import { Button } from "@/components/ui/button"
import { SVGProps } from "react"

export function Navbar() {
  return (
    <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6 bg-[#f0f8ff]">
      <Link href="#" className="mr-6 hidden lg:flex" prefetch={false}>
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">Omega</span>
      </Link>
      <NavigationMenu className="flex w-full justify-center">
        <NavigationMenuList>
          <NavigationMenuItem>
            <NavigationMenuTrigger className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f0f8ff] px-4 py-2 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50">
              Regalos
            </NavigationMenuTrigger>
            <NavigationMenuContent>
              <div className="grid w-[400px] p-2">
                <NavigationMenuLink asChild>
                  <Link
                    href="#"
                    className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-[#f0f8ff] p-4 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50"
                    prefetch={false}
                  >
                    <div className="text-sm font-medium leading-none group-hover:underline">Cumpleaños</div>
                    <div className="line-clamp-2 text-sm leading-snug text-[#87ceeb]">
                      Regalos para celebrar cumpleaños.
                    </div>
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link
                    href="#"
                    className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-[#f0f8ff] p-4 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50"
                    prefetch={false}
                  >
                    <div className="text-sm font-medium leading-none group-hover:underline">Aniversario</div>
                    <div className="line-clamp-2 text-sm leading-snug text-[#87ceeb]">
                      Regalos para celebrar aniversarios.
                    </div>
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link
                    href="#"
                    className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-[#f0f8ff] p-4 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50"
                    prefetch={false}
                  >
                    <div className="text-sm font-medium leading-none group-hover:underline">Navidad</div>
                    <div className="line-clamp-2 text-sm leading-snug text-[#87ceeb]">
                      Regalos para celebrar la Navidad.
                    </div>
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link
                    href="#"
                    className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-[#f0f8ff] p-4 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50"
                    prefetch={false}
                  >
                    <div className="text-sm font-medium leading-none group-hover:underline">San Valentín</div>
                    <div className="line-clamp-2 text-sm leading-snug text-[#87ceeb]">
                      Regalos para celebrar el Día de San Valentín.
                    </div>
                  </Link>
                </NavigationMenuLink>
              </div>
            </NavigationMenuContent>
          </NavigationMenuItem>
          <NavigationMenuItem>
            <NavigationMenuTrigger className="group inline-flex h-9 w-max items-center justify-center rounded-md bg-[#f0f8ff] px-4 py-2 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50">
              Papelería
            </NavigationMenuTrigger>
            <NavigationMenuContent>
              <div className="grid w-[400px] p-2">
                <NavigationMenuLink asChild>
                  <Link
                    href="#"
                    className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-[#f0f8ff] p-4 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50"
                    prefetch={false}
                  >
                    <div className="text-sm font-medium leading-none group-hover:underline">Cuadernos</div>
                    <div className="line-clamp-2 text-sm leading-snug text-[#87ceeb]">
                      Cuadernos de diferentes tamaños y diseños.
                    </div>
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link
                    href="#"
                    className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-[#f0f8ff] p-4 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50"
                    prefetch={false}
                  >
                    <div className="text-sm font-medium leading-none group-hover:underline">Bolígrafos</div>
                    <div className="line-clamp-2 text-sm leading-snug text-[#87ceeb]">
                      Bolígrafos de diferentes colores y estilos.
                    </div>
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link
                    href="#"
                    className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-[#f0f8ff] p-4 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50"
                    prefetch={false}
                  >
                    <div className="text-sm font-medium leading-none group-hover:underline">Agendas</div>
                    <div className="line-clamp-2 text-sm leading-snug text-[#87ceeb]">
                      Agendas para organizar tus actividades.
                    </div>
                  </Link>
                </NavigationMenuLink>
                <NavigationMenuLink asChild>
                  <Link
                    href="#"
                    className="group grid h-auto w-full items-center justify-start gap-1 rounded-md bg-[#f0f8ff] p-4 text-sm font-medium text-[#87ceeb] transition-colors hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none disabled:pointer-events-none disabled:opacity-50 data-[active]:bg-[#add8e6]/50 data-[state=open]:bg-[#add8e6]/50"
                    prefetch={false}
                  >
                    <div className="text-sm font-medium leading-none group-hover:underline">Papelería Decorativa</div>
                    <div className="line-clamp-2 text-sm leading-snug text-[#87ceeb]">
                      Papelería con diseños y estampados.
                    </div>
                  </Link>
                </NavigationMenuLink>
              </div>
            </NavigationMenuContent>
          </NavigationMenuItem>
        </NavigationMenuList>
      </NavigationMenu>
      <div className="ml-auto flex gap-2">
        <Button
          variant="outline"
          className="text-[#87ceeb] hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none"
        >
          Registrarme
        </Button>
          <link href="" /><button>Iniciar Sesion</button><Button className="bg-[#87ceeb] text-[#f0f8ff] hover:bg-[#add8e6] focus:bg-[#add8e6] focus:outline-none">
        </Button>
        <Button
          variant="outline"
          size="icon"
          className="text-[#87ceeb] hover:bg-[#add8e6] hover:text-[#f0f8ff] focus:bg-[#add8e6] focus:text-[#f0f8ff] focus:outline-none"
        >
          <ShoppingCartIcon className="h-6 w-6" />
          <span className="sr-only">Carrito de compras</span>
        </Button>
      </div>
    </header>
  )
}

function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function ShoppingCartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}
